export const referenceData = [
  {
    title: "Gimnazija 'Stevan Sremac' u Nišu",
    investor: "Investitor: Gramont",
    subject: "Predmet: Fasadna stolarija",
    date: "Datum: Jun 2010",
    srcImg: "/images/Reference/Borstil-reference-1.jpg",
  },
  {
    title: "Sudnica u Staroj Pazovi",
    investor: "Investitor: Zlatibor-gradnja",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: Septembar 2015",
    srcImg: "/images/Reference/Borstil-reference-10.jpg",
  },
  {
    title: "Specijalna bolnica u Bukovičkoj Banji",
    investor: "Investitor: Expertuniversal",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: Mart 2018",
    srcImg: "/images/Reference/Borstil-reference-13.jpg",
  },

  {
    title: "Banovina u Nišu",
    investor: "Investitor: Gramont",
    subject: "Predmet: Fasadna stolarija",
    date: "Datum: Septembar 2010",
    srcImg: "/images/Reference/Borstil-reference-2.jpg",
  },
  {
    title: "Dom JNA u Vranju",
    investor: "Investitor: Tončev gradnja",
    subject: "Predmet: Fasadna stolarija",
    date: "Datum: Septembar 2010",
    srcImg: "/images/Reference/Borstil-reference-6.jpg",
  },
  {
    title: "OŠ 'Ivan Goran Kovačić' u Beogradu",
    investor: "Investitor: Zlatibor-gradnja",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: April 2015",
    srcImg: "/images/Reference/Borstil-reference-7.jpg",
  },
  {
    title: "OŠ 'Sveti Sava' u Pirotu",
    investor: "Investitor: Expertuniversal",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: Jun 2010",
    srcImg: "/images/Reference/Borstil-reference-3.jpg",
  },
  {
    title: "Stambena zgrada",
    investor: "Investitor: Zlatibor-gradnja ",
    subject: "Predmet: Fasadna stolarija",
    date: "Datum: Septembar 2010",
    srcImg: "/images/Reference/Borstil-reference-4.jpg",
  },
  {
    title: "Stambena zgrada",
    investor: "Investitor: Zlatibor-gradnja ",
    subject: "Predmet: Fasadna stolarija",
    date: "Datum: Septembar 2010",
    srcImg: "/images/Reference/Borstil-reference-9.jpg",
  },

  {
    title: "KBC u Zemunu",
    investor: "Investitor: Graditelj",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: Septembar 2015",
    srcImg: "/images/Reference/Borstil-reference-11.jpg",
  },
  {
    title: "OŠ 'Dragojlo Dudić' u Beogradu",
    investor: "Investitor: Zlatibor-gradnja",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: Avgust 2016",
    srcImg: "/images/Reference/Borstil-reference-12.jpg",
  },

  {
    title: "Škola u Irigu",
    investor: "Investitor: BDM Gradnja, Vranic",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: Maj 2018",
    srcImg: "/images/Reference/Borstil-reference-14.jpg",
  },
  {
    title: "OŠ '1300 kaplara' u Beogradu",
    investor: "Investitor: Expertuniversal",
    subject: "Predmet: Unutrašnja vrata i opremanje učionica i kabineta",
    date: "Datum: Oktobar 2019",
    srcImg: "/images/Reference/Borstil-reference-15.jpg",
  },
  {
    title: "Muzej Kralja Petra u Topoli",
    investor: "Investitor: Expertuniversal",
    subject: "Predmet: Unutrašnja i fasadna stolarija",
    date: "Datum: Novembar 2016",
    srcImg: "/images/Reference/Borstil-reference-16.jpg",
  },
  {
    title: "Prihvatilište za decu",
    investor: "Investitor: Zlatibor-gradnja",
    subject: "Predmet: Unutrašnja stolarija",
    date: "Datum: Maj 2018",
    srcImg: "/images/Reference/Borstil-reference-17.jpg",
  },
  {
    title: "KO u Ovči u Beogradu, objekti 2a i 2b",
    investor: "Investitor: M Enterijer-gradnja",
    subject: "Predmet: Unutrašnja stolarija",
    date: "Datum: Avgust 2018",
    srcImg: "/images/Reference/Borstil-reference-18.jpg",
  },
  {
    title: "Prekršajni sud u Užicu",
    investor: "Investitor: Zlatibor-gradnja",
    subject: "Predmet: Unutrašnja vrata",
    date: "Datum: Januar 2017",
    srcImg: "/images/Reference/Borstil-reference-19.jpg",
  },
  {
    title: "OŠ 'Vasa Pelagić' u Ovči",
    investor: "Investitor: Zlatibor-gradnja",
    subject: "Predmet: Unutrašnja vrata i podprozorske daske",
    date: "Datum: Jun 2011",
    srcImg: "/images/Reference/Borstil-reference-20.jpg",
  },
];
