export const galleryData = [
  {
    title: "door",
    width: "960",
    height: "1200",
    imgSrc: "/images/Gallery/Borstil-vrata-6.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "1080",
    height: "810",
    imgSrc: "/images/Gallery/Borstil-vrata-3.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-2.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "1080",
    height: "1080",
    imgSrc: "/images/Gallery/Borstil-vrata-5.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "640",
    height: "800",
    imgSrc: "/images/Gallery/Borstil-vrata-1.jpg",
    tags: [
      "vrata",
      "medijapan",
      "sobna",
      "klizna",
      "schiebetüren",
      "tür",
      "türen",
      "mediapan",
    ],
  },
  {
    title: "kitchen",
    width: "960",
    height: "720",
    imgSrc: "/images/Gallery/Borstil-kuhinja-1.jpg",
    tags: ["kuhinja", "kuhinje", "küche"],
  },
  {
    title: "door",
    width: "1080",
    height: "1350",
    imgSrc: "/images/Gallery/Borstil-vrata-4.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-7.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "640",
    height: "789",
    imgSrc: "/images/Gallery/Borstil-vrata-8.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "1080",
    height: "1080",
    imgSrc: "/images/Gallery/Borstil-vrata-9.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-11.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "750",
    height: "575",
    imgSrc: "/images/Gallery/Borstil-vrata-15.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "750",
    height: "557",
    imgSrc: "/images/Gallery/Borstil-vrata-12.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-16.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "640",
    height: "800",
    imgSrc: "/images/Gallery/Borstil-vrata-17.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "kitchen",
    width: "960",
    height: "720",
    imgSrc: "/images/Gallery/Borstil-kuhinja-2.jpg",
    tags: ["kuhinja", "kuhinje", "küche"],
  },
  {
    title: "door",
    width: "640",
    height: "800",
    imgSrc: "/images/Gallery/Borstil-vrata-13.jpg",
    tags: [
      "vrata",
      "medijapan",
      "sobna",
      "klizna",
      "schiebetüren",
      "tür",
      "türen",
      "mediapan",
    ],
  },
  {
    title: "table&chairs",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-sto&stolice-1.jpg",
    tags: [
      "sto",
      "stolovi",
      "stolica",
      "stolice",
      "klupa",
      "klupe",
      "klupica",
      "klupice",
      "tabelle",
      "stuhl",
      "stühle",
      "bank",
      "bänke",
    ],
  },
  {
    title: "door",
    width: "750",
    height: "436",
    imgSrc: "/images/Gallery/Borstil-vrata-18.jpg",
    tags: [
      "vrata",
      "medijapan",
      "sobna",
      "klizna",
      "schiebetüren",
      "tür",
      "türen",
      "mediapan",
    ],
  },
  {
    title: "door",
    width: "750",
    height: "460",
    imgSrc: "/images/Gallery/Borstil-vrata-19.jpg",
    tags: [
      "vrata",
      "medijapan",
      "sobna",
      "klizna",
      "schiebetüren",
      "tür",
      "türen",
      "mediapan",
    ],
  },
  {
    title: "table&chairs",
    width: "750",
    height: "422",
    imgSrc: "/images/Gallery/Borstil-sto&stolice-2.jpg",
    tags: [
      "sto",
      "stolovi",
      "stolica",
      "stolice",
      "tabelle",
      "stuhl",
      "stühle",
    ],
  },
];

export const homeGalleryData = [
  {
    title: "door",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-16.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "1080",
    height: "810",
    imgSrc: "/images/Gallery/Borstil-vrata-3.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "960",
    height: "1200",
    imgSrc: "/images/Gallery/Borstil-vrata-6.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "1080",
    height: "1080",
    imgSrc: "/images/Gallery/Borstil-vrata-5.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "kitchen",
    width: "960",
    height: "720",
    imgSrc: "/images/Gallery/Borstil-kuhinja-1.jpg",
    tags: ["kuhinja", "kuhinje", "küche"],
  },

  {
    title: "door",
    width: "1080",
    height: "1350",
    imgSrc: "/images/Gallery/Borstil-vrata-4.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "750",
    height: "575",
    imgSrc: "/images/Gallery/Borstil-vrata-15.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "640",
    height: "790",
    imgSrc: "/images/Gallery/Borstil-vrata-1.jpg",
    tags: [
      "vrata",
      "medijapan",
      "sobna",
      "klizna",
      "schiebetüren",
      "tür",
      "türen",
      "mediapan",
    ],
  },

  {
    title: "door",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-11.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "640",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-8.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "door",
    width: "1080",
    height: "910",
    imgSrc: "/images/Gallery/Borstil-vrata-9.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  {
    title: "door",
    width: "750",
    height: "740",
    imgSrc: "/images/Gallery/Borstil-vrata-7.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
  {
    title: "kitchen",
    width: "960",
    height: "720",
    imgSrc: "/images/Gallery/Borstil-kuhinja-2.jpg",
    tags: ["kuhinja", "kuhinje", "küche"],
  },

  // {
  //   title: "door",
  //   width: "750",
  //   height: "557",
  //   imgSrc: "/images/Gallery/Borstil-vrata-12.jpg",
  //   tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  // },
  {
    title: "door",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-vrata-2.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },

  // {
  //   title: "door",
  //   width: "640",
  //   height: "800",
  //   imgSrc: "/images/Gallery/Borstil-vrata-13.jpg",
  //   tags: [
  //     "vrata",
  //     "medijapan",
  //     "sobna",
  //     "klizna",
  //     "schiebetüren",
  //     "tür",
  //     "türen",
  //     "mediapan",
  //   ],
  // },
  {
    title: "table&chairs",
    width: "750",
    height: "750",
    imgSrc: "/images/Gallery/Borstil-sto&stolice-1.jpg",
    tags: [
      "sto",
      "stolovi",
      "stolica",
      "stolice",
      "klupa",
      "klupe",
      "klupica",
      "klupice",
      "tabelle",
      "stuhl",
      "stühle",
      "bank",
      "bänke",
    ],
  },
  {
    title: "door",
    width: "640",
    height: "800",
    imgSrc: "/images/Gallery/Borstil-vrata-17.jpg",
    tags: ["vrata", "medijapan", "sobna", "tür", "türen", "mediapan"],
  },
];
